name: GDP Dashboard app

on:
  push:
    branches:
      - '**'  # This triggers the build and test on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  
        with:
          fetch-depth: 1

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v2  
        with:
          python-version: 3.12.4
      
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install project
        run: poetry install --no-interaction

      - name: Lint with flake8
        run: |
          poetry run pip install flake8
          poetry run flake8 . --count --select=E402,F401,F811,F841 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          poetry run pytest

  deploy: 
    if: github.ref == 'refs/heads/main'  # Ensures this job only runs on main branch
    runs-on: ubuntu-latest
    needs: build  # Deploy only runs if build is successful

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  
        with:
          fetch-depth: 1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gdp-dash
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/gdp-dash/gdp-dash:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/gdp-dash/gdp-dash:latest
          service: gdp-dash
          region: europe-north1
          allow-unauthenticated: true
